//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Address.
        /// </summary>
        public static string common_address {
            get {
                return ResourceManager.GetString("common_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_article {
            get {
                return ResourceManager.GetString("common_article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 character max..
        /// </summary>
        public static string common_code {
            get {
                return ResourceManager.GetString("common_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Mismatch.
        /// </summary>
        public static string common_confirm_password {
            get {
                return ResourceManager.GetString("common_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_description {
            get {
                return ResourceManager.GetString("common_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits Only.
        /// </summary>
        public static string common_digits {
            get {
                return ResourceManager.GetString("common_digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.example.com.
        /// </summary>
        public static string common_domain {
            get {
                return ResourceManager.GetString("common_domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string common_email {
            get {
                return ResourceManager.GetString("common_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_full_name {
            get {
                return ResourceManager.GetString("common_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_iso_date {
            get {
                return ResourceManager.GetString("common_iso_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_iso_datetime {
            get {
                return ResourceManager.GetString("common_iso_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_iso_time {
            get {
                return ResourceManager.GetString("common_iso_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_latitude {
            get {
                return ResourceManager.GetString("common_latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_long_text {
            get {
                return ResourceManager.GetString("common_long_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_longitude {
            get {
                return ResourceManager.GetString("common_longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75 characters max..
        /// </summary>
        public static string common_lookup {
            get {
                return ResourceManager.GetString("common_lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_map_location {
            get {
                return ResourceManager.GetString("common_map_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75 characters max..
        /// </summary>
        public static string common_name {
            get {
                return ResourceManager.GetString("common_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid national ID.
        /// </summary>
        public static string common_national_id {
            get {
                return ResourceManager.GetString("common_national_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000 characters max..
        /// </summary>
        public static string common_notes {
            get {
                return ResourceManager.GetString("common_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Number.
        /// </summary>
        public static string common_number {
            get {
                return ResourceManager.GetString("common_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string common_passport_number {
            get {
                return ResourceManager.GetString("common_passport_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 charachters min, 15 max..
        /// </summary>
        public static string common_password {
            get {
                return ResourceManager.GetString("common_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 digits min, 16 max..
        /// </summary>
        public static string common_phone {
            get {
                return ResourceManager.GetString("common_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 characters min, 10 max..
        /// </summary>
        public static string common_post_code {
            get {
                return ResourceManager.GetString("common_post_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid..
        /// </summary>
        public static string common_profile {
            get {
                return ResourceManager.GetString("common_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reference.
        /// </summary>
        public static string common_reference_number {
            get {
                return ResourceManager.GetString("common_reference_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Remarks.
        /// </summary>
        public static string common_remarks {
            get {
                return ResourceManager.GetString("common_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Required.
        /// </summary>
        public static string common_required {
            get {
                return ResourceManager.GetString("common_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Revision.
        /// </summary>
        public static string common_revision_number {
            get {
                return ResourceManager.GetString("common_revision_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 character max..
        /// </summary>
        public static string common_short_text {
            get {
                return ResourceManager.GetString("common_short_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 character max..
        /// </summary>
        public static string common_single_name {
            get {
                return ResourceManager.GetString("common_single_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 125 character max..
        /// </summary>
        public static string common_standard_text {
            get {
                return ResourceManager.GetString("common_standard_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150 character max..
        /// </summary>
        public static string common_title {
            get {
                return ResourceManager.GetString("common_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Url.
        /// </summary>
        public static string common_url {
            get {
                return ResourceManager.GetString("common_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 characters min, 50 max..
        /// </summary>
        public static string common_username {
            get {
                return ResourceManager.GetString("common_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Items cannot be changed because you have sent invitations to contacts..
        /// </summary>
        public static string enquiry_invitations_sent {
            get {
                return ResourceManager.GetString("enquiry_invitations_sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide data in correct format.
        /// </summary>
        public static string http_bad_request {
            get {
                return ResourceManager.GetString("http_bad_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process request at server, sorry for inconvenience.
        /// </summary>
        public static string http_internal_server_error {
            get {
                return ResourceManager.GetString("http_internal_server_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide data in correct format.
        /// </summary>
        public static string http_invalid_request {
            get {
                return ResourceManager.GetString("http_invalid_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item requested cannot be found.
        /// </summary>
        public static string http_not_found {
            get {
                return ResourceManager.GetString("http_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 character max..
        /// </summary>
        public static string public_user_code {
            get {
                return ResourceManager.GetString("public_user_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Exists.
        /// </summary>
        public static string public_user_user_exists {
            get {
                return ResourceManager.GetString("public_user_user_exists", resourceCulture);
            }
        }
    }
}
