//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Front {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Front() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Front", typeof(Front).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password.
        /// </summary>
        public static string activation_subject {
            get {
                return ResourceManager.GetString("activation_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string ads {
            get {
                return ResourceManager.GetString("ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string direction {
            get {
                return ResourceManager.GetString("direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min of 5 charcters &amp; max of 255..
        /// </summary>
        public static string error_address {
            get {
                return ResourceManager.GetString("error_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your data is correct.
        /// </summary>
        public static string error_bad_request {
            get {
                return ResourceManager.GetString("error_bad_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max of 2000 character.
        /// </summary>
        public static string error_description {
            get {
                return ResourceManager.GetString("error_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid email.
        /// </summary>
        public static string error_email {
            get {
                return ResourceManager.GetString("error_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! an error has occured, please try again later..
        /// </summary>
        public static string error_generic_internal_server {
            get {
                return ResourceManager.GetString("error_generic_internal_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get your current location, please make sure your GPS is enabled and working properly..
        /// </summary>
        public static string error_gps {
            get {
                return ResourceManager.GetString("error_gps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid activation code.
        /// </summary>
        public static string error_invalid_code {
            get {
                return ResourceManager.GetString("error_invalid_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to required data are not valid.
        /// </summary>
        public static string error_not_found {
            get {
                return ResourceManager.GetString("error_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked, call us for more information..
        /// </summary>
        public static string error_user_blocked {
            get {
                return ResourceManager.GetString("error_user_blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists, please proceed to login directly..
        /// </summary>
        public static string error_user_exits {
            get {
                return ResourceManager.GetString("error_user_exits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account found for this number, please register first..
        /// </summary>
        public static string error_user_not_exist {
            get {
                return ResourceManager.GetString("error_user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to login first..
        /// </summary>
        public static string info_login_first {
            get {
                return ResourceManager.GetString("info_login_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string msg_continue {
            get {
                return ResourceManager.GetString("msg_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msg_error {
            get {
                return ResourceManager.GetString("msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string msg_info {
            get {
                return ResourceManager.GetString("msg_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string msg_thanks {
            get {
                return ResourceManager.GetString("msg_thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string msg_warning {
            get {
                return ResourceManager.GetString("msg_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _EN.
        /// </summary>
        public static string postfix {
            get {
                return ResourceManager.GetString("postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string regions {
            get {
                return ResourceManager.GetString("regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Services.
        /// </summary>
        public static string service_requests {
            get {
                return ResourceManager.GetString("service_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Saved.
        /// </summary>
        public static string success_profile_updated {
            get {
                return ResourceManager.GetString("success_profile_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thnaks, you have registered sucessfully..
        /// </summary>
        public static string success_registration {
            get {
                return ResourceManager.GetString("success_registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request has been saved, we will call you as soon..
        /// </summary>
        public static string success_request {
            get {
                return ResourceManager.GetString("success_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Details.
        /// </summary>
        public static string views_ad_details {
            get {
                return ResourceManager.GetString("views_ad_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string views_address {
            get {
                return ResourceManager.GetString("views_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string views_ads {
            get {
                return ResourceManager.GetString("views_ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string views_categories {
            get {
                return ResourceManager.GetString("views_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string views_category_details {
            get {
                return ResourceManager.GetString("views_category_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request This Service.
        /// </summary>
        public static string views_category_details_request {
            get {
                return ResourceManager.GetString("views_category_details_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string views_city {
            get {
                return ResourceManager.GetString("views_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested work to be done.
        /// </summary>
        public static string views_description {
            get {
                return ResourceManager.GetString("views_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string views_email {
            get {
                return ResourceManager.GetString("views_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid phone..
        /// </summary>
        public static string views_error_phone {
            get {
                return ResourceManager.GetString("views_error_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * required.
        /// </summary>
        public static string views_error_required {
            get {
                return ResourceManager.GetString("views_error_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string views_home {
            get {
                return ResourceManager.GetString("views_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string views_login {
            get {
                return ResourceManager.GetString("views_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your mobile number and the activation code that has been sent to you..
        /// </summary>
        public static string views_login_description {
            get {
                return ResourceManager.GetString("views_login_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string views_login_submit {
            get {
                return ResourceManager.GetString("views_login_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string views_logout {
            get {
                return ResourceManager.GetString("views_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string views_map {
            get {
                return ResourceManager.GetString("views_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string views_map_continue {
            get {
                return ResourceManager.GetString("views_map_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnCall.
        /// </summary>
        public static string views_menu_header {
            get {
                return ResourceManager.GetString("views_menu_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string views_mobile_phone {
            get {
                return ResourceManager.GetString("views_mobile_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Ads.
        /// </summary>
        public static string views_more {
            get {
                return ResourceManager.GetString("views_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string views_name {
            get {
                return ResourceManager.GetString("views_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string views_other_language {
            get {
                return ResourceManager.GetString("views_other_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string views_otp {
            get {
                return ResourceManager.GetString("views_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid mobile number. An activation code will be sent to this number to continue your request..
        /// </summary>
        public static string views_otp_description {
            get {
                return ResourceManager.GetString("views_otp_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have the code and want to continue directly.
        /// </summary>
        public static string views_otp_skip {
            get {
                return ResourceManager.GetString("views_otp_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request New Code.
        /// </summary>
        public static string views_otp_submit {
            get {
                return ResourceManager.GetString("views_otp_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string views_profile {
            get {
                return ResourceManager.GetString("views_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can modify these info..
        /// </summary>
        public static string views_profile_description {
            get {
                return ResourceManager.GetString("views_profile_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string views_profile_submit {
            get {
                return ResourceManager.GetString("views_profile_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string views_region {
            get {
                return ResourceManager.GetString("views_region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string views_register {
            get {
                return ResourceManager.GetString("views_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the following data and the activation code sent to you..
        /// </summary>
        public static string views_register_description {
            get {
                return ResourceManager.GetString("views_register_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string views_register_submit {
            get {
                return ResourceManager.GetString("views_register_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Service.
        /// </summary>
        public static string views_request {
            get {
                return ResourceManager.GetString("views_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide requested work to be done. You can attach a photo to help your description..
        /// </summary>
        public static string views_request_description {
            get {
                return ResourceManager.GetString("views_request_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string views_request_details {
            get {
                return ResourceManager.GetString("views_request_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string views_request_submit {
            get {
                return ResourceManager.GetString("views_request_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string views_requests {
            get {
                return ResourceManager.GetString("views_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Photo.
        /// </summary>
        public static string views_take_photo {
            get {
                return ResourceManager.GetString("views_take_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Camera.
        /// </summary>
        public static string views_take_photo__from_camera {
            get {
                return ResourceManager.GetString("views_take_photo__from_camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Gallery.
        /// </summary>
        public static string views_take_photo__from_memory {
            get {
                return ResourceManager.GetString("views_take_photo__from_memory", resourceCulture);
            }
        }
    }
}
