//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mail() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Mail", typeof(Mail).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Pool : Activation Code.
        /// </summary>
        public static string activation_subject {
            get {
                return ResourceManager.GetString("activation_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Pool : Info.
        /// </summary>
        public static string default_subject {
            get {
                return ResourceManager.GetString("default_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Pool: Invitation Reponse.
        /// </summary>
        public static string invitation_response_subject {
            get {
                return ResourceManager.GetString("invitation_response_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Pool: Invitation.
        /// </summary>
        public static string invitation_subject {
            get {
                return ResourceManager.GetString("invitation_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Poolr: One Time Password.
        /// </summary>
        public static string otp_subject {
            get {
                return ResourceManager.GetString("otp_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Request Pool.
        /// </summary>
        public static string registration_subject {
            get {
                return ResourceManager.GetString("registration_subject", resourceCulture);
            }
        }
    }
}
