//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string administrator_confirm_password {
            get {
                return ResourceManager.GetString("administrator_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string administrator_email {
            get {
                return ResourceManager.GetString("administrator_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string administrator_name {
            get {
                return ResourceManager.GetString("administrator_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string administrator_password {
            get {
                return ResourceManager.GetString("administrator_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string administrator_phone_number {
            get {
                return ResourceManager.GetString("administrator_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string administrator_update_password {
            get {
                return ResourceManager.GetString("administrator_update_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string administrator_username {
            get {
                return ResourceManager.GetString("administrator_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string administrators_is_active {
            get {
                return ResourceManager.GetString("administrators_is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string client {
            get {
                return ResourceManager.GetString("client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string common_address {
            get {
                return ResourceManager.GetString("common_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string common_birthdate {
            get {
                return ResourceManager.GetString("common_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string common_code {
            get {
                return ResourceManager.GetString("common_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string common_company_name {
            get {
                return ResourceManager.GetString("common_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string common_confirm_password {
            get {
                return ResourceManager.GetString("common_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string common_creation_date {
            get {
                return ResourceManager.GetString("common_creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string common_creator {
            get {
                return ResourceManager.GetString("common_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string common_date {
            get {
                return ResourceManager.GetString("common_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string common_description {
            get {
                return ResourceManager.GetString("common_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string common_email {
            get {
                return ResourceManager.GetString("common_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string common_end_date {
            get {
                return ResourceManager.GetString("common_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string common_fax {
            get {
                return ResourceManager.GetString("common_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string common_geolocation {
            get {
                return ResourceManager.GetString("common_geolocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string common_ip {
            get {
                return ResourceManager.GetString("common_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string common_is_active {
            get {
                return ResourceManager.GetString("common_is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string common_is_default {
            get {
                return ResourceManager.GetString("common_is_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Front.
        /// </summary>
        public static string common_is_front {
            get {
                return ResourceManager.GetString("common_is_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string common_is_public {
            get {
                return ResourceManager.GetString("common_is_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string common_job {
            get {
                return ResourceManager.GetString("common_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string common_last_update_date {
            get {
                return ResourceManager.GetString("common_last_update_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string common_name {
            get {
                return ResourceManager.GetString("common_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string common_national_id {
            get {
                return ResourceManager.GetString("common_national_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string common_nationality {
            get {
                return ResourceManager.GetString("common_nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string common_new_password {
            get {
                return ResourceManager.GetString("common_new_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string common_notes {
            get {
                return ResourceManager.GetString("common_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string common_old_password {
            get {
                return ResourceManager.GetString("common_old_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string common_passport {
            get {
                return ResourceManager.GetString("common_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string common_password {
            get {
                return ResourceManager.GetString("common_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string common_phone {
            get {
                return ResourceManager.GetString("common_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string common_photo {
            get {
                return ResourceManager.GetString("common_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string common_post_date {
            get {
                return ResourceManager.GetString("common_post_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string common_profile {
            get {
                return ResourceManager.GetString("common_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string common_qualification {
            get {
                return ResourceManager.GetString("common_qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string common_rank {
            get {
                return ResourceManager.GetString("common_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        public static string common_reference_number {
            get {
                return ResourceManager.GetString("common_reference_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string common_remarks {
            get {
                return ResourceManager.GetString("common_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision Number.
        /// </summary>
        public static string common_revision_number {
            get {
                return ResourceManager.GetString("common_revision_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string common_search {
            get {
                return ResourceManager.GetString("common_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string common_start_date {
            get {
                return ResourceManager.GetString("common_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string common_subject {
            get {
                return ResourceManager.GetString("common_subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string common_title {
            get {
                return ResourceManager.GetString("common_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string common_username {
            get {
                return ResourceManager.GetString("common_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string common_value {
            get {
                return ResourceManager.GetString("common_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string common_website {
            get {
                return ResourceManager.GetString("common_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Category.
        /// </summary>
        public static string contact_type {
            get {
                return ResourceManager.GetString("contact_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Revision.
        /// </summary>
        public static string enquiries_parent {
            get {
                return ResourceManager.GetString("enquiries_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry.
        /// </summary>
        public static string enquiry {
            get {
                return ResourceManager.GetString("enquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOQ#.
        /// </summary>
        public static string enquiry_boq_number {
            get {
                return ResourceManager.GetString("enquiry_boq_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR#.
        /// </summary>
        public static string enquiry_pr_number {
            get {
                return ResourceManager.GetString("enquiry_pr_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string enquiry_status {
            get {
                return ResourceManager.GetString("enquiry_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Type.
        /// </summary>
        public static string enquiry_type {
            get {
                return ResourceManager.GetString("enquiry_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation.
        /// </summary>
        public static string invitation {
            get {
                return ResourceManager.GetString("invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Till.
        /// </summary>
        public static string invitation_end_date {
            get {
                return ResourceManager.GetString("invitation_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string invitation_post_date {
            get {
                return ResourceManager.GetString("invitation_post_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string item_response {
            get {
                return ResourceManager.GetString("item_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare.
        /// </summary>
        public static string item_response_compare {
            get {
                return ResourceManager.GetString("item_response_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lookup_name {
            get {
                return ResourceManager.GetString("lookup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumption.
        /// </summary>
        public static string membership_consumption {
            get {
                return ResourceManager.GetString("membership_consumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Contacts.
        /// </summary>
        public static string membership_consumption_contacts_per_invitation {
            get {
                return ResourceManager.GetString("membership_consumption_contacts_per_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiries.
        /// </summary>
        public static string membership_consumption_enquiries {
            get {
                return ResourceManager.GetString("membership_consumption_enquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations.
        /// </summary>
        public static string membership_consumption_invitations {
            get {
                return ResourceManager.GetString("membership_consumption_invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Properties.
        /// </summary>
        public static string membership_consumption_item_fields {
            get {
                return ResourceManager.GetString("membership_consumption_item_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Items.
        /// </summary>
        public static string membership_consumption_items_per_enquiry {
            get {
                return ResourceManager.GetString("membership_consumption_items_per_enquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrade To.
        /// </summary>
        public static string membership_downgrade_plan {
            get {
                return ResourceManager.GetString("membership_downgrade_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string membership_end_date {
            get {
                return ResourceManager.GetString("membership_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string membership_history {
            get {
                return ResourceManager.GetString("membership_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string membership_payment {
            get {
                return ResourceManager.GetString("membership_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memebership Plan.
        /// </summary>
        public static string membership_plan {
            get {
                return ResourceManager.GetString("membership_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Cost.
        /// </summary>
        public static string membership_plan_cost_per_month {
            get {
                return ResourceManager.GetString("membership_plan_cost_per_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Cost.
        /// </summary>
        public static string membership_plan_cost_per_year {
            get {
                return ResourceManager.GetString("membership_plan_cost_per_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per year.
        /// </summary>
        public static string membership_plan_cost_per_year1 {
            get {
                return ResourceManager.GetString("membership_plan_cost_per_year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string membership_plan_description {
            get {
                return ResourceManager.GetString("membership_plan_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max contacts per invitation.
        /// </summary>
        public static string membership_plan_max_contacts_per_invitation {
            get {
                return ResourceManager.GetString("membership_plan_max_contacts_per_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max enquiries per month.
        /// </summary>
        public static string membership_plan_max_enquiries_per_month {
            get {
                return ResourceManager.GetString("membership_plan_max_enquiries_per_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max inquiry fields.
        /// </summary>
        public static string membership_plan_max_enquiry_fields {
            get {
                return ResourceManager.GetString("membership_plan_max_enquiry_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max invitations per month.
        /// </summary>
        public static string membership_plan_max_invitations_per_month {
            get {
                return ResourceManager.GetString("membership_plan_max_invitations_per_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max item fields.
        /// </summary>
        public static string membership_plan_max_item_fields {
            get {
                return ResourceManager.GetString("membership_plan_max_item_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max items per request.
        /// </summary>
        public static string membership_plan_max_items_per_enquiry {
            get {
                return ResourceManager.GetString("membership_plan_max_items_per_enquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max request fields.
        /// </summary>
        public static string membership_plan_max_request_fields {
            get {
                return ResourceManager.GetString("membership_plan_max_request_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max requests per inquiry.
        /// </summary>
        public static string membership_plan_max_requests_per_inquiry {
            get {
                return ResourceManager.GetString("membership_plan_max_requests_per_inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string membership_plan_title {
            get {
                return ResourceManager.GetString("membership_plan_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string membership_start_date {
            get {
                return ResourceManager.GetString("membership_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string public_user_company_name {
            get {
                return ResourceManager.GetString("public_user_company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string public_user_name {
            get {
                return ResourceManager.GetString("public_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password.
        /// </summary>
        public static string public_user_otp {
            get {
                return ResourceManager.GetString("public_user_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string public_user_profile {
            get {
                return ResourceManager.GetString("public_user_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request New OTP.
        /// </summary>
        public static string public_user_update_otp {
            get {
                return ResourceManager.GetString("public_user_update_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string public_user_update_password {
            get {
                return ResourceManager.GetString("public_user_update_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Selected.
        /// </summary>
        public static string recipient_response_compare {
            get {
                return ResourceManager.GetString("recipient_response_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Date.
        /// </summary>
        public static string recipient_submit_date {
            get {
                return ResourceManager.GetString("recipient_submit_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipients.
        /// </summary>
        public static string recipients {
            get {
                return ResourceManager.GetString("recipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Date.
        /// </summary>
        public static string response_post_date {
            get {
                return ResourceManager.GetString("response_post_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string response_sender {
            get {
                return ResourceManager.GetString("response_sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
    }
}
