//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Admin.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string administrator_confirm_password {
            get {
                return ResourceManager.GetString("administrator_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string administrator_email {
            get {
                return ResourceManager.GetString("administrator_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string administrator_name {
            get {
                return ResourceManager.GetString("administrator_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string administrator_password {
            get {
                return ResourceManager.GetString("administrator_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string administrator_phone_number {
            get {
                return ResourceManager.GetString("administrator_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string administrator_update_password {
            get {
                return ResourceManager.GetString("administrator_update_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string administrator_username {
            get {
                return ResourceManager.GetString("administrator_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string administrators_is_active {
            get {
                return ResourceManager.GetString("administrators_is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string common_address {
            get {
                return ResourceManager.GetString("common_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string common_birthdate {
            get {
                return ResourceManager.GetString("common_birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string common_company {
            get {
                return ResourceManager.GetString("common_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string common_confirm_password {
            get {
                return ResourceManager.GetString("common_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string common_creation_date {
            get {
                return ResourceManager.GetString("common_creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string common_creator {
            get {
                return ResourceManager.GetString("common_creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string common_date {
            get {
                return ResourceManager.GetString("common_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string common_description {
            get {
                return ResourceManager.GetString("common_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string common_email {
            get {
                return ResourceManager.GetString("common_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string common_end_date {
            get {
                return ResourceManager.GetString("common_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string common_fax {
            get {
                return ResourceManager.GetString("common_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string common_is_active {
            get {
                return ResourceManager.GetString("common_is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string common_is_default {
            get {
                return ResourceManager.GetString("common_is_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Front.
        /// </summary>
        public static string common_is_front {
            get {
                return ResourceManager.GetString("common_is_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string common_is_public {
            get {
                return ResourceManager.GetString("common_is_public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string common_job {
            get {
                return ResourceManager.GetString("common_job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string common_last_update_date {
            get {
                return ResourceManager.GetString("common_last_update_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string common_national_id {
            get {
                return ResourceManager.GetString("common_national_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string common_nationality {
            get {
                return ResourceManager.GetString("common_nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string common_notes {
            get {
                return ResourceManager.GetString("common_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string common_passport {
            get {
                return ResourceManager.GetString("common_passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string common_password {
            get {
                return ResourceManager.GetString("common_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string common_phone {
            get {
                return ResourceManager.GetString("common_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string common_photo {
            get {
                return ResourceManager.GetString("common_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string common_qualification {
            get {
                return ResourceManager.GetString("common_qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string common_rank {
            get {
                return ResourceManager.GetString("common_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string common_remarks {
            get {
                return ResourceManager.GetString("common_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string common_search {
            get {
                return ResourceManager.GetString("common_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string common_start_date {
            get {
                return ResourceManager.GetString("common_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string common_title {
            get {
                return ResourceManager.GetString("common_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string common_username {
            get {
                return ResourceManager.GetString("common_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string common_website {
            get {
                return ResourceManager.GetString("common_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lookup_name {
            get {
                return ResourceManager.GetString("lookup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downgrade To.
        /// </summary>
        public static string membership_downgrade_plan {
            get {
                return ResourceManager.GetString("membership_downgrade_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memebership Plan.
        /// </summary>
        public static string membership_plan {
            get {
                return ResourceManager.GetString("membership_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per month.
        /// </summary>
        public static string membership_plan_cost_per_month {
            get {
                return ResourceManager.GetString("membership_plan_cost_per_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost per year.
        /// </summary>
        public static string membership_plan_cost_per_year {
            get {
                return ResourceManager.GetString("membership_plan_cost_per_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max contacts per invitation.
        /// </summary>
        public static string membership_plan_max_contacts_per_invitation {
            get {
                return ResourceManager.GetString("membership_plan_max_contacts_per_invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max enquiries per month.
        /// </summary>
        public static string membership_plan_max_enquiries_per_month {
            get {
                return ResourceManager.GetString("membership_plan_max_enquiries_per_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max inquiry fields.
        /// </summary>
        public static string membership_plan_max_enquiry_fields {
            get {
                return ResourceManager.GetString("membership_plan_max_enquiry_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max invitations per month.
        /// </summary>
        public static string membership_plan_max_invitations_per_month {
            get {
                return ResourceManager.GetString("membership_plan_max_invitations_per_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max item fields.
        /// </summary>
        public static string membership_plan_max_item_fields {
            get {
                return ResourceManager.GetString("membership_plan_max_item_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max items per request.
        /// </summary>
        public static string membership_plan_max_items_per_enquiry {
            get {
                return ResourceManager.GetString("membership_plan_max_items_per_enquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max request fields.
        /// </summary>
        public static string membership_plan_max_request_fields {
            get {
                return ResourceManager.GetString("membership_plan_max_request_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max requests per inquiry.
        /// </summary>
        public static string membership_plan_max_requests_per_inquiry {
            get {
                return ResourceManager.GetString("membership_plan_max_requests_per_inquiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        public static string property_type {
            get {
                return ResourceManager.GetString("property_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string public_user_name {
            get {
                return ResourceManager.GetString("public_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password.
        /// </summary>
        public static string public_user_otp {
            get {
                return ResourceManager.GetString("public_user_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request New OTP.
        /// </summary>
        public static string public_user_update_otp {
            get {
                return ResourceManager.GetString("public_user_update_otp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string public_user_update_password {
            get {
                return ResourceManager.GetString("public_user_update_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
    }
}
