//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Roles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Roles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Admin.Roles", typeof(Roles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Administrators.
        /// </summary>
        public static string manage_admins {
            get {
                return ResourceManager.GetString("manage_admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Lookups.
        /// </summary>
        public static string manage_lookups {
            get {
                return ResourceManager.GetString("manage_lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Membership.
        /// </summary>
        public static string manage_membership {
            get {
                return ResourceManager.GetString("manage_membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string manage_public_users {
            get {
                return ResourceManager.GetString("manage_public_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Reports.
        /// </summary>
        public static string manage_reports {
            get {
                return ResourceManager.GetString("manage_reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Settings.
        /// </summary>
        public static string manage_settings {
            get {
                return ResourceManager.GetString("manage_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Clients.
        /// </summary>
        public static string view_clients {
            get {
                return ResourceManager.GetString("view_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contact Types.
        /// </summary>
        public static string view_contact_types {
            get {
                return ResourceManager.GetString("view_contact_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contacts.
        /// </summary>
        public static string view_contacts {
            get {
                return ResourceManager.GetString("view_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Enquiries.
        /// </summary>
        public static string view_enquiries {
            get {
                return ResourceManager.GetString("view_enquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Enquiry Types.
        /// </summary>
        public static string view_enquiry_types {
            get {
                return ResourceManager.GetString("view_enquiry_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Inbox.
        /// </summary>
        public static string view_inbox {
            get {
                return ResourceManager.GetString("view_inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Item Properties.
        /// </summary>
        public static string view_item_properties {
            get {
                return ResourceManager.GetString("view_item_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Item Types.
        /// </summary>
        public static string view_item_types {
            get {
                return ResourceManager.GetString("view_item_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Projects.
        /// </summary>
        public static string view_projects {
            get {
                return ResourceManager.GetString("view_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Templates.
        /// </summary>
        public static string view_templates {
            get {
                return ResourceManager.GetString("view_templates", resourceCulture);
            }
        }
    }
}
