//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Admin.Views", typeof(Views).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string administrators {
            get {
                return ResourceManager.GetString("administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Administrators.
        /// </summary>
        public static string administrators_manage {
            get {
                return ResourceManager.GetString("administrators_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrators.
        /// </summary>
        public static string admins {
            get {
                return ResourceManager.GetString("admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string clients {
            get {
                return ResourceManager.GetString("clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Categories.
        /// </summary>
        public static string contact_categories {
            get {
                return ResourceManager.GetString("contact_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiries.
        /// </summary>
        public static string enquiries {
            get {
                return ResourceManager.GetString("enquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Types.
        /// </summary>
        public static string enquiry_types {
            get {
                return ResourceManager.GetString("enquiry_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved Invitations.
        /// </summary>
        public static string inbox {
            get {
                return ResourceManager.GetString("inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Types.
        /// </summary>
        public static string item_types {
            get {
                return ResourceManager.GetString("item_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Clients.
        /// </summary>
        public static string manage_clients {
            get {
                return ResourceManager.GetString("manage_clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Contacts.
        /// </summary>
        public static string manage_contacts {
            get {
                return ResourceManager.GetString("manage_contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Enquiries.
        /// </summary>
        public static string manage_enquiries {
            get {
                return ResourceManager.GetString("manage_enquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Membership Plans.
        /// </summary>
        public static string manage_membership_plans {
            get {
                return ResourceManager.GetString("manage_membership_plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Projects.
        /// </summary>
        public static string manage_projects {
            get {
                return ResourceManager.GetString("manage_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string membership {
            get {
                return ResourceManager.GetString("membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Plans.
        /// </summary>
        public static string membership_plans {
            get {
                return ResourceManager.GetString("membership_plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string public_users {
            get {
                return ResourceManager.GetString("public_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string public_users_manage {
            get {
                return ResourceManager.GetString("public_users_manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string regions {
            get {
                return ResourceManager.GetString("regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
    }
}
