namespace Infrastructure.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class change_int_to_bigint : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ApplicationUserClaims", "UserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ApplicationUsers", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ApplicationUserLogins", "UserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ApplicationUserRoles", "UserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Clients", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Projects", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryAttachments", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Enquiries", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryTypes", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryTypes", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Items", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ItemTypes", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ItemTypes", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Clients", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Memberships", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.MembershipPlans", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Memberships", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Countries", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Cities", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Regions", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ContactTypes", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ContactTypes", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Contacts", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Contacts", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryResponses", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryResponses", "RecipientId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Invitations", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Recipients", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ItemResponses", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Recipients", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Otps", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Settings", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Status", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Status", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Projects", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Enquiries", "ProjectId", "dbo.Projects");
            DropForeignKey("dbo.EnquiryAttachments", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.Items", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.EnquiryResponses", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.Invitations", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.Enquiries", "EnquiryTypeId", "dbo.EnquiryTypes");
            DropForeignKey("dbo.ItemResponses", "ItemId", "dbo.Items");
            DropForeignKey("dbo.Items", "ItemTypeId", "dbo.ItemTypes");
            DropForeignKey("dbo.Memberships", "DowngradeToMembershipPlanId", "dbo.MembershipPlans");
            DropForeignKey("dbo.Memberships", "MembershipPlanId", "dbo.MembershipPlans");
            DropForeignKey("dbo.Regions", "CityId", "dbo.Cities");
            DropForeignKey("dbo.Cities", "CountryId", "dbo.Countries");
            DropForeignKey("dbo.Recipients", "ContactId", "dbo.Contacts");
            DropForeignKey("dbo.Contacts", "ContactTypeId", "dbo.ContactTypes");
            DropForeignKey("dbo.Recipients", "InvitationId", "dbo.Invitations");
            DropForeignKey("dbo.ItemResponses", "RecipientId", "dbo.Recipients");
            DropForeignKey("dbo.ApplicationUserRoles", "RoleId", "dbo.ApplicationRoles");
            DropIndex("dbo.ApplicationUsers", new[] { "CreatorId" });
            DropIndex("dbo.ApplicationUserClaims", new[] { "UserId" });
            DropIndex("dbo.ApplicationUserLogins", new[] { "UserId" });
            DropIndex("dbo.ApplicationUserRoles", new[] { "UserId" });
            DropIndex("dbo.ApplicationUserRoles", new[] { "RoleId" });
            DropIndex("dbo.Clients", new[] { "PublicUserId" });
            DropIndex("dbo.Clients", new[] { "CreatorId" });
            DropIndex("dbo.Projects", new[] { "ClientId" });
            DropIndex("dbo.Projects", new[] { "CreatorId" });
            DropIndex("dbo.Enquiries", new[] { "EnquiryTypeId" });
            DropIndex("dbo.Enquiries", new[] { "ProjectId" });
            DropIndex("dbo.Enquiries", new[] { "CreatorId" });
            DropIndex("dbo.EnquiryAttachments", new[] { "EnquiryId" });
            DropIndex("dbo.EnquiryAttachments", new[] { "CreatorId" });
            DropIndex("dbo.EnquiryTypes", new[] { "PublicUserId" });
            DropIndex("dbo.EnquiryTypes", new[] { "CreatorId" });
            DropIndex("dbo.Items", new[] { "ItemTypeId" });
            DropIndex("dbo.Items", new[] { "EnquiryId" });
            DropIndex("dbo.Items", new[] { "CreatorId" });
            DropIndex("dbo.ItemTypes", new[] { "PublicUserId" });
            DropIndex("dbo.ItemTypes", new[] { "CreatorId" });
            DropIndex("dbo.Memberships", new[] { "MembershipPlanId" });
            DropIndex("dbo.Memberships", new[] { "DowngradeToMembershipPlanId" });
            DropIndex("dbo.Memberships", new[] { "PublicUserId" });
            DropIndex("dbo.Memberships", new[] { "CreatorId" });
            DropIndex("dbo.MembershipPlans", new[] { "CreatorId" });
            DropIndex("dbo.Cities", new[] { "CountryId" });
            DropIndex("dbo.Cities", new[] { "CreatorId" });
            DropIndex("dbo.Countries", new[] { "CreatorId" });
            DropIndex("dbo.Regions", new[] { "CityId" });
            DropIndex("dbo.Regions", new[] { "CreatorId" });
            DropIndex("dbo.Contacts", new[] { "PublicUserId" });
            DropIndex("dbo.Contacts", new[] { "ContactTypeId" });
            DropIndex("dbo.Contacts", new[] { "CreatorId" });
            DropIndex("dbo.ContactTypes", new[] { "PublicUserId" });
            DropIndex("dbo.ContactTypes", new[] { "CreatorId" });
            DropIndex("dbo.EnquiryResponses", new[] { "RecipientId" });
            DropIndex("dbo.EnquiryResponses", new[] { "EnquiryId" });
            DropIndex("dbo.EnquiryResponses", new[] { "CreatorId" });
            DropIndex("dbo.Invitations", new[] { "EnquiryId" });
            DropIndex("dbo.Invitations", new[] { "CreatorId" });
            DropIndex("dbo.Recipients", new[] { "ContactId" });
            DropIndex("dbo.Recipients", new[] { "PublicUserId" });
            DropIndex("dbo.Recipients", new[] { "InvitationId" });
            DropIndex("dbo.Recipients", new[] { "CreatorId" });
            DropIndex("dbo.ItemResponses", new[] { "RecipientId" });
            DropIndex("dbo.ItemResponses", new[] { "ItemId" });
            DropIndex("dbo.ItemResponses", new[] { "CreatorId" });
            DropIndex("dbo.Otps", new[] { "CreatorId" });
            DropIndex("dbo.Settings", new[] { "CreatorId" });
            DropIndex("dbo.Status", new[] { "PublicUserId" });
            DropIndex("dbo.Status", new[] { "CreatorId" });
            DropPrimaryKey("dbo.ApplicationUsers");
            DropPrimaryKey("dbo.ApplicationUserLogins");
            DropPrimaryKey("dbo.ApplicationUserRoles");
            DropPrimaryKey("dbo.Clients");
            DropPrimaryKey("dbo.Projects");
            DropPrimaryKey("dbo.Enquiries");
            DropPrimaryKey("dbo.EnquiryAttachments");
            DropPrimaryKey("dbo.EnquiryTypes");
            DropPrimaryKey("dbo.Items");
            DropPrimaryKey("dbo.ItemTypes");
            DropPrimaryKey("dbo.Memberships");
            DropPrimaryKey("dbo.MembershipPlans");
            DropPrimaryKey("dbo.Cities");
            DropPrimaryKey("dbo.Countries");
            DropPrimaryKey("dbo.Regions");
            DropPrimaryKey("dbo.Contacts");
            DropPrimaryKey("dbo.ContactTypes");
            DropPrimaryKey("dbo.EnquiryResponses");
            DropPrimaryKey("dbo.Invitations");
            DropPrimaryKey("dbo.Recipients");
            DropPrimaryKey("dbo.ItemResponses");
            DropPrimaryKey("dbo.Otps");
            DropPrimaryKey("dbo.ApplicationRoles");
            DropPrimaryKey("dbo.Settings");
            DropPrimaryKey("dbo.Status");
            AlterColumn("dbo.ApplicationUsers", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ApplicationUsers", "CreatorId", c => c.Long());
            AlterColumn("dbo.ApplicationUserClaims", "UserId", c => c.Long(nullable: false));
            AlterColumn("dbo.ApplicationUserLogins", "UserId", c => c.Long(nullable: false));
            AlterColumn("dbo.ApplicationUserRoles", "UserId", c => c.Long(nullable: false));
            AlterColumn("dbo.ApplicationUserRoles", "RoleId", c => c.Long(nullable: false));
            AlterColumn("dbo.Clients", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Clients", "PublicUserId", c => c.Long(nullable: false));
            AlterColumn("dbo.Clients", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Projects", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Projects", "ClientId", c => c.Long(nullable: false));
            AlterColumn("dbo.Projects", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Enquiries", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Enquiries", "EnquiryTypeId", c => c.Long(nullable: false));
            AlterColumn("dbo.Enquiries", "ProjectId", c => c.Long(nullable: false));
            AlterColumn("dbo.Enquiries", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.EnquiryAttachments", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.EnquiryAttachments", "EnquiryId", c => c.Long(nullable: false));
            AlterColumn("dbo.EnquiryAttachments", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.EnquiryTypes", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.EnquiryTypes", "PublicUserId", c => c.Long(nullable: false));
            AlterColumn("dbo.EnquiryTypes", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Items", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Items", "ItemTypeId", c => c.Long());
            AlterColumn("dbo.Items", "EnquiryId", c => c.Long(nullable: false));
            AlterColumn("dbo.Items", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.ItemTypes", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ItemTypes", "PublicUserId", c => c.Long(nullable: false));
            AlterColumn("dbo.ItemTypes", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Memberships", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Memberships", "MembershipPlanId", c => c.Long(nullable: false));
            AlterColumn("dbo.Memberships", "DowngradeToMembershipPlanId", c => c.Long());
            AlterColumn("dbo.Memberships", "PublicUserId", c => c.Long(nullable: false));
            AlterColumn("dbo.Memberships", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.MembershipPlans", "MaxEnquiriesPerMonth", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxRequestsPerEnquiry", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxItemsPerEnquiry", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxInvitationsPerMonth", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxContactsPerInvitation", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxEnquiryFields", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxRequestFields", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxItemFields", c => c.Long(nullable: false));
            AlterColumn("dbo.MembershipPlans", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Cities", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Cities", "Rank", c => c.Long(nullable: false));
            AlterColumn("dbo.Cities", "CountryId", c => c.Long(nullable: false));
            AlterColumn("dbo.Cities", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Countries", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Countries", "Rank", c => c.Long(nullable: false));
            AlterColumn("dbo.Countries", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Regions", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Regions", "Rank", c => c.Long(nullable: false));
            AlterColumn("dbo.Regions", "CityId", c => c.Long(nullable: false));
            AlterColumn("dbo.Regions", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Contacts", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Contacts", "PublicUserId", c => c.Long(nullable: false));
            AlterColumn("dbo.Contacts", "ContactTypeId", c => c.Long(nullable: false));
            AlterColumn("dbo.Contacts", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.ContactTypes", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ContactTypes", "PublicUserId", c => c.Long(nullable: false));
            AlterColumn("dbo.ContactTypes", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.EnquiryResponses", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.EnquiryResponses", "RecipientId", c => c.Long(nullable: false));
            AlterColumn("dbo.EnquiryResponses", "EnquiryId", c => c.Long(nullable: false));
            AlterColumn("dbo.EnquiryResponses", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Invitations", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Invitations", "EnquiryId", c => c.Long(nullable: false));
            AlterColumn("dbo.Invitations", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Recipients", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Recipients", "ContactId", c => c.Long(nullable: false));
            AlterColumn("dbo.Recipients", "PublicUserId", c => c.Long());
            AlterColumn("dbo.Recipients", "InvitationId", c => c.Long(nullable: false));
            AlterColumn("dbo.Recipients", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.ItemResponses", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.ItemResponses", "RecipientId", c => c.Long(nullable: false));
            AlterColumn("dbo.ItemResponses", "ItemId", c => c.Long(nullable: false));
            AlterColumn("dbo.ItemResponses", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Otps", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Otps", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.ApplicationRoles", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Settings", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Settings", "DefaultMembershipPeriod", c => c.Long(nullable: false));
            AlterColumn("dbo.Settings", "CreatorId", c => c.Long(nullable: false));
            AlterColumn("dbo.Status", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Status", "Rank", c => c.Long(nullable: false));
            AlterColumn("dbo.Status", "PublicUserId", c => c.Long(nullable: false));
            AlterColumn("dbo.Status", "CreatorId", c => c.Long(nullable: false));
            AddPrimaryKey("dbo.ApplicationUsers", "Id");
            AddPrimaryKey("dbo.ApplicationUserLogins", new[] { "LoginProvider", "ProviderKey", "UserId" });
            AddPrimaryKey("dbo.ApplicationUserRoles", new[] { "UserId", "RoleId" });
            AddPrimaryKey("dbo.Clients", "Id");
            AddPrimaryKey("dbo.Projects", "Id");
            AddPrimaryKey("dbo.Enquiries", "Id");
            AddPrimaryKey("dbo.EnquiryAttachments", "Id");
            AddPrimaryKey("dbo.EnquiryTypes", "Id");
            AddPrimaryKey("dbo.Items", "Id");
            AddPrimaryKey("dbo.ItemTypes", "Id");
            AddPrimaryKey("dbo.Memberships", "Id");
            AddPrimaryKey("dbo.MembershipPlans", "Id");
            AddPrimaryKey("dbo.Cities", "Id");
            AddPrimaryKey("dbo.Countries", "Id");
            AddPrimaryKey("dbo.Regions", "Id");
            AddPrimaryKey("dbo.Contacts", "Id");
            AddPrimaryKey("dbo.ContactTypes", "Id");
            AddPrimaryKey("dbo.EnquiryResponses", "Id");
            AddPrimaryKey("dbo.Invitations", "Id");
            AddPrimaryKey("dbo.Recipients", "Id");
            AddPrimaryKey("dbo.ItemResponses", "Id");
            AddPrimaryKey("dbo.Otps", "Id");
            AddPrimaryKey("dbo.ApplicationRoles", "Id");
            AddPrimaryKey("dbo.Settings", "Id");
            AddPrimaryKey("dbo.Status", "Id");
            CreateIndex("dbo.ApplicationUsers", "CreatorId");
            CreateIndex("dbo.ApplicationUserClaims", "UserId");
            CreateIndex("dbo.ApplicationUserLogins", "UserId");
            CreateIndex("dbo.ApplicationUserRoles", "UserId");
            CreateIndex("dbo.ApplicationUserRoles", "RoleId");
            CreateIndex("dbo.Clients", "PublicUserId");
            CreateIndex("dbo.Clients", "CreatorId");
            CreateIndex("dbo.Projects", "ClientId");
            CreateIndex("dbo.Projects", "CreatorId");
            CreateIndex("dbo.Enquiries", "EnquiryTypeId");
            CreateIndex("dbo.Enquiries", "ProjectId");
            CreateIndex("dbo.Enquiries", "CreatorId");
            CreateIndex("dbo.EnquiryAttachments", "EnquiryId");
            CreateIndex("dbo.EnquiryAttachments", "CreatorId");
            CreateIndex("dbo.EnquiryTypes", "PublicUserId");
            CreateIndex("dbo.EnquiryTypes", "CreatorId");
            CreateIndex("dbo.Items", "ItemTypeId");
            CreateIndex("dbo.Items", "EnquiryId");
            CreateIndex("dbo.Items", "CreatorId");
            CreateIndex("dbo.ItemTypes", "PublicUserId");
            CreateIndex("dbo.ItemTypes", "CreatorId");
            CreateIndex("dbo.Memberships", "MembershipPlanId");
            CreateIndex("dbo.Memberships", "DowngradeToMembershipPlanId");
            CreateIndex("dbo.Memberships", "PublicUserId");
            CreateIndex("dbo.Memberships", "CreatorId");
            CreateIndex("dbo.MembershipPlans", "CreatorId");
            CreateIndex("dbo.Cities", "CountryId");
            CreateIndex("dbo.Cities", "CreatorId");
            CreateIndex("dbo.Countries", "CreatorId");
            CreateIndex("dbo.Regions", "CityId");
            CreateIndex("dbo.Regions", "CreatorId");
            CreateIndex("dbo.Contacts", "PublicUserId");
            CreateIndex("dbo.Contacts", "ContactTypeId");
            CreateIndex("dbo.Contacts", "CreatorId");
            CreateIndex("dbo.ContactTypes", "PublicUserId");
            CreateIndex("dbo.ContactTypes", "CreatorId");
            CreateIndex("dbo.EnquiryResponses", "RecipientId");
            CreateIndex("dbo.EnquiryResponses", "EnquiryId");
            CreateIndex("dbo.EnquiryResponses", "CreatorId");
            CreateIndex("dbo.Invitations", "EnquiryId");
            CreateIndex("dbo.Invitations", "CreatorId");
            CreateIndex("dbo.Recipients", "ContactId");
            CreateIndex("dbo.Recipients", "PublicUserId");
            CreateIndex("dbo.Recipients", "InvitationId");
            CreateIndex("dbo.Recipients", "CreatorId");
            CreateIndex("dbo.ItemResponses", "RecipientId");
            CreateIndex("dbo.ItemResponses", "ItemId");
            CreateIndex("dbo.ItemResponses", "CreatorId");
            CreateIndex("dbo.Otps", "CreatorId");
            CreateIndex("dbo.Settings", "CreatorId");
            CreateIndex("dbo.Status", "PublicUserId");
            CreateIndex("dbo.Status", "CreatorId");
            AddForeignKey("dbo.ApplicationUserClaims", "UserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ApplicationUsers", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ApplicationUserLogins", "UserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ApplicationUserRoles", "UserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Clients", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Projects", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryAttachments", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Enquiries", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryTypes", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryTypes", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Items", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ItemTypes", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ItemTypes", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Clients", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Memberships", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.MembershipPlans", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Memberships", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Countries", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Cities", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Regions", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ContactTypes", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ContactTypes", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Contacts", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Contacts", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryResponses", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryResponses", "RecipientId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Invitations", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Recipients", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ItemResponses", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Recipients", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Otps", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Settings", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Status", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Status", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Projects", "ClientId", "dbo.Clients", "Id");
            AddForeignKey("dbo.Enquiries", "ProjectId", "dbo.Projects", "Id");
            AddForeignKey("dbo.EnquiryAttachments", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.Items", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.EnquiryResponses", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.Invitations", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.Enquiries", "EnquiryTypeId", "dbo.EnquiryTypes", "Id");
            AddForeignKey("dbo.ItemResponses", "ItemId", "dbo.Items", "Id");
            AddForeignKey("dbo.Items", "ItemTypeId", "dbo.ItemTypes", "Id");
            AddForeignKey("dbo.Memberships", "DowngradeToMembershipPlanId", "dbo.MembershipPlans", "Id");
            AddForeignKey("dbo.Memberships", "MembershipPlanId", "dbo.MembershipPlans", "Id");
            AddForeignKey("dbo.Regions", "CityId", "dbo.Cities", "Id");
            AddForeignKey("dbo.Cities", "CountryId", "dbo.Countries", "Id");
            AddForeignKey("dbo.Recipients", "ContactId", "dbo.Contacts", "Id");
            AddForeignKey("dbo.Contacts", "ContactTypeId", "dbo.ContactTypes", "Id");
            AddForeignKey("dbo.Recipients", "InvitationId", "dbo.Invitations", "Id");
            AddForeignKey("dbo.ItemResponses", "RecipientId", "dbo.Recipients", "Id");
            AddForeignKey("dbo.ApplicationUserRoles", "RoleId", "dbo.ApplicationRoles", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.ApplicationUserRoles", "RoleId", "dbo.ApplicationRoles");
            DropForeignKey("dbo.ItemResponses", "RecipientId", "dbo.Recipients");
            DropForeignKey("dbo.Recipients", "InvitationId", "dbo.Invitations");
            DropForeignKey("dbo.Contacts", "ContactTypeId", "dbo.ContactTypes");
            DropForeignKey("dbo.Recipients", "ContactId", "dbo.Contacts");
            DropForeignKey("dbo.Cities", "CountryId", "dbo.Countries");
            DropForeignKey("dbo.Regions", "CityId", "dbo.Cities");
            DropForeignKey("dbo.Memberships", "MembershipPlanId", "dbo.MembershipPlans");
            DropForeignKey("dbo.Memberships", "DowngradeToMembershipPlanId", "dbo.MembershipPlans");
            DropForeignKey("dbo.Items", "ItemTypeId", "dbo.ItemTypes");
            DropForeignKey("dbo.ItemResponses", "ItemId", "dbo.Items");
            DropForeignKey("dbo.Enquiries", "EnquiryTypeId", "dbo.EnquiryTypes");
            DropForeignKey("dbo.Invitations", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.EnquiryResponses", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.Items", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.EnquiryAttachments", "EnquiryId", "dbo.Enquiries");
            DropForeignKey("dbo.Enquiries", "ProjectId", "dbo.Projects");
            DropForeignKey("dbo.Projects", "ClientId", "dbo.Clients");
            DropForeignKey("dbo.Status", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Status", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Settings", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Otps", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Recipients", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ItemResponses", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Recipients", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Invitations", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryResponses", "RecipientId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryResponses", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Contacts", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Contacts", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ContactTypes", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ContactTypes", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Regions", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Cities", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Countries", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Memberships", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.MembershipPlans", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Memberships", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Clients", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ItemTypes", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ItemTypes", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Items", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryTypes", "PublicUserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryTypes", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Enquiries", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.EnquiryAttachments", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Projects", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.Clients", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ApplicationUserRoles", "UserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ApplicationUserLogins", "UserId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ApplicationUsers", "CreatorId", "dbo.ApplicationUsers");
            DropForeignKey("dbo.ApplicationUserClaims", "UserId", "dbo.ApplicationUsers");
            DropIndex("dbo.Status", new[] { "CreatorId" });
            DropIndex("dbo.Status", new[] { "PublicUserId" });
            DropIndex("dbo.Settings", new[] { "CreatorId" });
            DropIndex("dbo.Otps", new[] { "CreatorId" });
            DropIndex("dbo.ItemResponses", new[] { "CreatorId" });
            DropIndex("dbo.ItemResponses", new[] { "ItemId" });
            DropIndex("dbo.ItemResponses", new[] { "RecipientId" });
            DropIndex("dbo.Recipients", new[] { "CreatorId" });
            DropIndex("dbo.Recipients", new[] { "InvitationId" });
            DropIndex("dbo.Recipients", new[] { "PublicUserId" });
            DropIndex("dbo.Recipients", new[] { "ContactId" });
            DropIndex("dbo.Invitations", new[] { "CreatorId" });
            DropIndex("dbo.Invitations", new[] { "EnquiryId" });
            DropIndex("dbo.EnquiryResponses", new[] { "CreatorId" });
            DropIndex("dbo.EnquiryResponses", new[] { "EnquiryId" });
            DropIndex("dbo.EnquiryResponses", new[] { "RecipientId" });
            DropIndex("dbo.ContactTypes", new[] { "CreatorId" });
            DropIndex("dbo.ContactTypes", new[] { "PublicUserId" });
            DropIndex("dbo.Contacts", new[] { "CreatorId" });
            DropIndex("dbo.Contacts", new[] { "ContactTypeId" });
            DropIndex("dbo.Contacts", new[] { "PublicUserId" });
            DropIndex("dbo.Regions", new[] { "CreatorId" });
            DropIndex("dbo.Regions", new[] { "CityId" });
            DropIndex("dbo.Countries", new[] { "CreatorId" });
            DropIndex("dbo.Cities", new[] { "CreatorId" });
            DropIndex("dbo.Cities", new[] { "CountryId" });
            DropIndex("dbo.MembershipPlans", new[] { "CreatorId" });
            DropIndex("dbo.Memberships", new[] { "CreatorId" });
            DropIndex("dbo.Memberships", new[] { "PublicUserId" });
            DropIndex("dbo.Memberships", new[] { "DowngradeToMembershipPlanId" });
            DropIndex("dbo.Memberships", new[] { "MembershipPlanId" });
            DropIndex("dbo.ItemTypes", new[] { "CreatorId" });
            DropIndex("dbo.ItemTypes", new[] { "PublicUserId" });
            DropIndex("dbo.Items", new[] { "CreatorId" });
            DropIndex("dbo.Items", new[] { "EnquiryId" });
            DropIndex("dbo.Items", new[] { "ItemTypeId" });
            DropIndex("dbo.EnquiryTypes", new[] { "CreatorId" });
            DropIndex("dbo.EnquiryTypes", new[] { "PublicUserId" });
            DropIndex("dbo.EnquiryAttachments", new[] { "CreatorId" });
            DropIndex("dbo.EnquiryAttachments", new[] { "EnquiryId" });
            DropIndex("dbo.Enquiries", new[] { "CreatorId" });
            DropIndex("dbo.Enquiries", new[] { "ProjectId" });
            DropIndex("dbo.Enquiries", new[] { "EnquiryTypeId" });
            DropIndex("dbo.Projects", new[] { "CreatorId" });
            DropIndex("dbo.Projects", new[] { "ClientId" });
            DropIndex("dbo.Clients", new[] { "CreatorId" });
            DropIndex("dbo.Clients", new[] { "PublicUserId" });
            DropIndex("dbo.ApplicationUserRoles", new[] { "RoleId" });
            DropIndex("dbo.ApplicationUserRoles", new[] { "UserId" });
            DropIndex("dbo.ApplicationUserLogins", new[] { "UserId" });
            DropIndex("dbo.ApplicationUserClaims", new[] { "UserId" });
            DropIndex("dbo.ApplicationUsers", new[] { "CreatorId" });
            DropPrimaryKey("dbo.Status");
            DropPrimaryKey("dbo.Settings");
            DropPrimaryKey("dbo.ApplicationRoles");
            DropPrimaryKey("dbo.Otps");
            DropPrimaryKey("dbo.ItemResponses");
            DropPrimaryKey("dbo.Recipients");
            DropPrimaryKey("dbo.Invitations");
            DropPrimaryKey("dbo.EnquiryResponses");
            DropPrimaryKey("dbo.ContactTypes");
            DropPrimaryKey("dbo.Contacts");
            DropPrimaryKey("dbo.Regions");
            DropPrimaryKey("dbo.Countries");
            DropPrimaryKey("dbo.Cities");
            DropPrimaryKey("dbo.MembershipPlans");
            DropPrimaryKey("dbo.Memberships");
            DropPrimaryKey("dbo.ItemTypes");
            DropPrimaryKey("dbo.Items");
            DropPrimaryKey("dbo.EnquiryTypes");
            DropPrimaryKey("dbo.EnquiryAttachments");
            DropPrimaryKey("dbo.Enquiries");
            DropPrimaryKey("dbo.Projects");
            DropPrimaryKey("dbo.Clients");
            DropPrimaryKey("dbo.ApplicationUserRoles");
            DropPrimaryKey("dbo.ApplicationUserLogins");
            DropPrimaryKey("dbo.ApplicationUsers");
            AlterColumn("dbo.Status", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Status", "PublicUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Status", "Rank", c => c.Int(nullable: false));
            AlterColumn("dbo.Status", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Settings", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Settings", "DefaultMembershipPeriod", c => c.Int(nullable: false));
            AlterColumn("dbo.Settings", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ApplicationRoles", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Otps", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Otps", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ItemResponses", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.ItemResponses", "ItemId", c => c.Int(nullable: false));
            AlterColumn("dbo.ItemResponses", "RecipientId", c => c.Int(nullable: false));
            AlterColumn("dbo.ItemResponses", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Recipients", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Recipients", "InvitationId", c => c.Int(nullable: false));
            AlterColumn("dbo.Recipients", "PublicUserId", c => c.Int());
            AlterColumn("dbo.Recipients", "ContactId", c => c.Int(nullable: false));
            AlterColumn("dbo.Recipients", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Invitations", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Invitations", "EnquiryId", c => c.Int(nullable: false));
            AlterColumn("dbo.Invitations", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.EnquiryResponses", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnquiryResponses", "EnquiryId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnquiryResponses", "RecipientId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnquiryResponses", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ContactTypes", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.ContactTypes", "PublicUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.ContactTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Contacts", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Contacts", "ContactTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Contacts", "PublicUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Contacts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Regions", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Regions", "CityId", c => c.Int(nullable: false));
            AlterColumn("dbo.Regions", "Rank", c => c.Int(nullable: false));
            AlterColumn("dbo.Regions", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Countries", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Countries", "Rank", c => c.Int(nullable: false));
            AlterColumn("dbo.Countries", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Cities", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Cities", "CountryId", c => c.Int(nullable: false));
            AlterColumn("dbo.Cities", "Rank", c => c.Int(nullable: false));
            AlterColumn("dbo.Cities", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.MembershipPlans", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxItemFields", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxRequestFields", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxEnquiryFields", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxContactsPerInvitation", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxInvitationsPerMonth", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxItemsPerEnquiry", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxRequestsPerEnquiry", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "MaxEnquiriesPerMonth", c => c.Int(nullable: false));
            AlterColumn("dbo.MembershipPlans", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Memberships", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Memberships", "PublicUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Memberships", "DowngradeToMembershipPlanId", c => c.Int());
            AlterColumn("dbo.Memberships", "MembershipPlanId", c => c.Int(nullable: false));
            AlterColumn("dbo.Memberships", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ItemTypes", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.ItemTypes", "PublicUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.ItemTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Items", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Items", "EnquiryId", c => c.Int(nullable: false));
            AlterColumn("dbo.Items", "ItemTypeId", c => c.Int());
            AlterColumn("dbo.Items", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.EnquiryTypes", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnquiryTypes", "PublicUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnquiryTypes", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.EnquiryAttachments", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnquiryAttachments", "EnquiryId", c => c.Int(nullable: false));
            AlterColumn("dbo.EnquiryAttachments", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Enquiries", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Enquiries", "ProjectId", c => c.Int(nullable: false));
            AlterColumn("dbo.Enquiries", "EnquiryTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Enquiries", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Projects", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Projects", "ClientId", c => c.Int(nullable: false));
            AlterColumn("dbo.Projects", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Clients", "CreatorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Clients", "PublicUserId", c => c.Int(nullable: false));
            AlterColumn("dbo.Clients", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.ApplicationUserRoles", "RoleId", c => c.Int(nullable: false));
            AlterColumn("dbo.ApplicationUserRoles", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.ApplicationUserLogins", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.ApplicationUserClaims", "UserId", c => c.Int(nullable: false));
            AlterColumn("dbo.ApplicationUsers", "CreatorId", c => c.Int());
            AlterColumn("dbo.ApplicationUsers", "Id", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.Status", "Id");
            AddPrimaryKey("dbo.Settings", "Id");
            AddPrimaryKey("dbo.ApplicationRoles", "Id");
            AddPrimaryKey("dbo.Otps", "Id");
            AddPrimaryKey("dbo.ItemResponses", "Id");
            AddPrimaryKey("dbo.Recipients", "Id");
            AddPrimaryKey("dbo.Invitations", "Id");
            AddPrimaryKey("dbo.EnquiryResponses", "Id");
            AddPrimaryKey("dbo.ContactTypes", "Id");
            AddPrimaryKey("dbo.Contacts", "Id");
            AddPrimaryKey("dbo.Regions", "Id");
            AddPrimaryKey("dbo.Countries", "Id");
            AddPrimaryKey("dbo.Cities", "Id");
            AddPrimaryKey("dbo.MembershipPlans", "Id");
            AddPrimaryKey("dbo.Memberships", "Id");
            AddPrimaryKey("dbo.ItemTypes", "Id");
            AddPrimaryKey("dbo.Items", "Id");
            AddPrimaryKey("dbo.EnquiryTypes", "Id");
            AddPrimaryKey("dbo.EnquiryAttachments", "Id");
            AddPrimaryKey("dbo.Enquiries", "Id");
            AddPrimaryKey("dbo.Projects", "Id");
            AddPrimaryKey("dbo.Clients", "Id");
            AddPrimaryKey("dbo.ApplicationUserRoles", new[] { "UserId", "RoleId" });
            AddPrimaryKey("dbo.ApplicationUserLogins", new[] { "LoginProvider", "ProviderKey", "UserId" });
            AddPrimaryKey("dbo.ApplicationUsers", "Id");
            CreateIndex("dbo.Status", "CreatorId");
            CreateIndex("dbo.Status", "PublicUserId");
            CreateIndex("dbo.Settings", "CreatorId");
            CreateIndex("dbo.Otps", "CreatorId");
            CreateIndex("dbo.ItemResponses", "CreatorId");
            CreateIndex("dbo.ItemResponses", "ItemId");
            CreateIndex("dbo.ItemResponses", "RecipientId");
            CreateIndex("dbo.Recipients", "CreatorId");
            CreateIndex("dbo.Recipients", "InvitationId");
            CreateIndex("dbo.Recipients", "PublicUserId");
            CreateIndex("dbo.Recipients", "ContactId");
            CreateIndex("dbo.Invitations", "CreatorId");
            CreateIndex("dbo.Invitations", "EnquiryId");
            CreateIndex("dbo.EnquiryResponses", "CreatorId");
            CreateIndex("dbo.EnquiryResponses", "EnquiryId");
            CreateIndex("dbo.EnquiryResponses", "RecipientId");
            CreateIndex("dbo.ContactTypes", "CreatorId");
            CreateIndex("dbo.ContactTypes", "PublicUserId");
            CreateIndex("dbo.Contacts", "CreatorId");
            CreateIndex("dbo.Contacts", "ContactTypeId");
            CreateIndex("dbo.Contacts", "PublicUserId");
            CreateIndex("dbo.Regions", "CreatorId");
            CreateIndex("dbo.Regions", "CityId");
            CreateIndex("dbo.Countries", "CreatorId");
            CreateIndex("dbo.Cities", "CreatorId");
            CreateIndex("dbo.Cities", "CountryId");
            CreateIndex("dbo.MembershipPlans", "CreatorId");
            CreateIndex("dbo.Memberships", "CreatorId");
            CreateIndex("dbo.Memberships", "PublicUserId");
            CreateIndex("dbo.Memberships", "DowngradeToMembershipPlanId");
            CreateIndex("dbo.Memberships", "MembershipPlanId");
            CreateIndex("dbo.ItemTypes", "CreatorId");
            CreateIndex("dbo.ItemTypes", "PublicUserId");
            CreateIndex("dbo.Items", "CreatorId");
            CreateIndex("dbo.Items", "EnquiryId");
            CreateIndex("dbo.Items", "ItemTypeId");
            CreateIndex("dbo.EnquiryTypes", "CreatorId");
            CreateIndex("dbo.EnquiryTypes", "PublicUserId");
            CreateIndex("dbo.EnquiryAttachments", "CreatorId");
            CreateIndex("dbo.EnquiryAttachments", "EnquiryId");
            CreateIndex("dbo.Enquiries", "CreatorId");
            CreateIndex("dbo.Enquiries", "ProjectId");
            CreateIndex("dbo.Enquiries", "EnquiryTypeId");
            CreateIndex("dbo.Projects", "CreatorId");
            CreateIndex("dbo.Projects", "ClientId");
            CreateIndex("dbo.Clients", "CreatorId");
            CreateIndex("dbo.Clients", "PublicUserId");
            CreateIndex("dbo.ApplicationUserRoles", "RoleId");
            CreateIndex("dbo.ApplicationUserRoles", "UserId");
            CreateIndex("dbo.ApplicationUserLogins", "UserId");
            CreateIndex("dbo.ApplicationUserClaims", "UserId");
            CreateIndex("dbo.ApplicationUsers", "CreatorId");
            AddForeignKey("dbo.ApplicationUserRoles", "RoleId", "dbo.ApplicationRoles", "Id");
            AddForeignKey("dbo.ItemResponses", "RecipientId", "dbo.Recipients", "Id");
            AddForeignKey("dbo.Recipients", "InvitationId", "dbo.Invitations", "Id");
            AddForeignKey("dbo.Contacts", "ContactTypeId", "dbo.ContactTypes", "Id");
            AddForeignKey("dbo.Recipients", "ContactId", "dbo.Contacts", "Id");
            AddForeignKey("dbo.Cities", "CountryId", "dbo.Countries", "Id");
            AddForeignKey("dbo.Regions", "CityId", "dbo.Cities", "Id");
            AddForeignKey("dbo.Memberships", "MembershipPlanId", "dbo.MembershipPlans", "Id");
            AddForeignKey("dbo.Memberships", "DowngradeToMembershipPlanId", "dbo.MembershipPlans", "Id");
            AddForeignKey("dbo.Items", "ItemTypeId", "dbo.ItemTypes", "Id");
            AddForeignKey("dbo.ItemResponses", "ItemId", "dbo.Items", "Id");
            AddForeignKey("dbo.Enquiries", "EnquiryTypeId", "dbo.EnquiryTypes", "Id");
            AddForeignKey("dbo.Invitations", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.EnquiryResponses", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.Items", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.EnquiryAttachments", "EnquiryId", "dbo.Enquiries", "Id");
            AddForeignKey("dbo.Enquiries", "ProjectId", "dbo.Projects", "Id");
            AddForeignKey("dbo.Projects", "ClientId", "dbo.Clients", "Id");
            AddForeignKey("dbo.Status", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Status", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Settings", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Otps", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Recipients", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ItemResponses", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Recipients", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Invitations", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryResponses", "RecipientId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryResponses", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Contacts", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Contacts", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ContactTypes", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ContactTypes", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Regions", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Cities", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Countries", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Memberships", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.MembershipPlans", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Memberships", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Clients", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ItemTypes", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ItemTypes", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Items", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryTypes", "PublicUserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryTypes", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Enquiries", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.EnquiryAttachments", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Projects", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.Clients", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ApplicationUserRoles", "UserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ApplicationUserLogins", "UserId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ApplicationUsers", "CreatorId", "dbo.ApplicationUsers", "Id");
            AddForeignKey("dbo.ApplicationUserClaims", "UserId", "dbo.ApplicationUsers", "Id");
        }
    }
}
