// <auto-generated />
namespace Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update11seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update11seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201712081425113_update-11-seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
