// <auto-generated />
namespace Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class change_int_to_bigint : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_int_to_bigint));
        
        string IMigrationMetadata.Id
        {
            get { return "201710111042063_change_int_to_bigint"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
