// <auto-generated />
namespace Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrecpientresponseattachments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrecpientresponseattachments));
        
        string IMigrationMetadata.Id
        {
            get { return "202011221518086_add-recpient-response-attachments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
